Polymer/polymer-cli

- custom_typings/dom5.d.ts
- custom_typings/hydrolysis.d.ts
- custom_typings/node.d.ts
- custom_typings/yeoman-environment.d.ts
- package.json
- src/build/build.ts
- src/build/html-project.ts
- src/build/stream-resolver.ts
- src/commands/build.ts
- src/commands/lint.ts
- src/commands/serve.ts
- src/polytool.ts
- tsconfig.json
This adds a generic build pipeline to polytool.
* Builds can be extended by the project gulpfile by exporting a `transforms` property.
* HTML files are split similar to crisper, but style should also be split (WIP), and they are recombined by default. script and style tags are not moved like in cripser.
* Vulcanize reads files from the gulp stream unlike default gulp-vulcanize. This means that transformed files are passed through vulcanize. I'm uncertain how well that actually works with normal gulp-vulcanize, as it might depend on the ordering and completeness of other transform steps and whether they've written to disk yet.
* entrypoints and source globs can be specified, but there's only support for a single entrypoint right now. This needs to be expanded to multiple entrypoints, and …
> Initial build pipeline

- package.json
`npm run init` & `npm run build` both failed to run on my machine (i don't have them installed globally). This adds them as local `devDependencies` where npm is able to find & use them via it's $PATH.
> add missing typings dependency

- src/build/logger.ts
- src/build/streams.ts
StreamLogger should call the callback
ForkedVinylStream should push `null` instead of emitting end on source
`end` event, as that may miss chunks sitting in the internal buffer.
Pushing `null` will let the buffer play out until it hits the null, when
the `end` event will emit itself.
> Fix busted streams

- src/build/build.ts
- src/build/sw-precache.ts
- src/commands/build.ts
Clean up deps pipeline by adding precache config file after optimization
pass with `passthrough` mode for vinyl-fs.src
> Add flag for service worker precache config file

- package.json
- src/build/build.ts
- src/build/optimize.ts
- src/build/stream-resolver.ts
- typings.json
We're now using `minimatch-all`
> Removes unused minimatch dependency, fixes broken tests

- package.json
- src/commands/help.ts
- src/polytool.ts
- test/commands/help_test.js
I cleaned up some of the code here and made the help output a little nicer. 
- New output (a few small changes here to improve readability)
- no command now outputs help instead of failing (see tests)
- unknown command now outputs help instead of failing (see tests)
CR @justinfagnani
> Cleanup help behavior and output

- .travis.yml
- package.json
Being explicit in both our package.json & travis testing is enough to handle #63 IMO. Now ff anyone tries to install the CLI with an earlier version of Node they'll get a warning at install time.
> Update package.json engines and travis version testing

- src/polymer-cli.ts
- test/commands/cli_test.js
- test/commands/help_test.js
Previously, both `--help/-h` & `--version/-v` flags would throw errors if they were used. To implement these across commands, the global `polymer-cli` now watches for and handles them.
CR @justinfagnani
> Support --help & --version flags

- package.json
- src/commands/init.ts
A small change related to #79. Since we care about loading time we should use this (arguably simpler) way to fix the `depcheck` error that the call to require `generator-polymer-init` originally silenced.
> Remove an unnecessary import and instead tell depcheck its safe to ignore

- src/commands/build.ts
- src/commands/init.ts
- src/commands/test.ts
Fixes #79
```
$ time polymer --version
real	0m2.667s
user	0m1.625s
sys	0m0.299s
```
```
$ time polymer --version
real	0m0.671s
user	0m0.511s
sys	0m0.073s
```
Each dependency that has been optimized to load at run-time was previously adding at least 300ms a piece to the overall load time. `PolykartGenerator` was adding 1 second!. The remaining ~670ms time is mostly taken up by loading the dependencies of `lint` & `serve`, which cannot be easily optimized because their commands rely on the arguments defined within their dependencies. We'll need to revisit this pattern if we want to optimize further.
> Optimize command imports to only load when command is run

- bin/polymer.js
- custom_typings/plylog.d.ts
- package.json
- src/commands/init.ts
- src/polymer-cli.ts
- test/commands/cli_test.js
- test/commands/help_test.js
- tsconfig.json
Fixes #95
This PR adds basic logging to the Main CLI runner, and the init command. Once this is merged we can logging to each of the other commands as needed.
We've built a simple logger to be shared across polymer CLIs & libraries. See https://github.com/Polymer/plylog/blob/master/index.js for the logic there & please open an issue if you have any comments there.
/cc @justinfagnani @azakus
> Add logging framework, add logging to main & init command

- src/commands/lint.ts
- src/commands/serve.ts
- src/polymer-cli.ts
Fixes #114 
Existing tests now catch duplicate argument definitions across all commands because the detection is done in the CLI constructor.
> Fix duplicate argument definitions.

- src/templates/polykart.ts
Fixes #57 and #40 
This seems to be the "yeoman way" to handle installing dependencies. It says "hey I'm installing all needed dependencies" (by checking for bower.json & package.json) "if anything fails make sure you look into it". It's also included in the TS definition while bowerInstall isn't, which is another good sign.
@addyosmani might be able to confirm that this is correct.
> Install dependencies via smarter yeoman method

- src/build/build.ts
Include all the fragments and shell, just as bundled build does
Fixes #128 Unbundled build is missing fragments and shell in sw-precache
> Make sure unbundled precache deps list is complete

- custom_typings/command-line-args.d.ts
- custom_typings/command-line-commands.d.ts
- src/args.ts
- src/commands/help.ts
- src/polymer-cli.ts
- tsconfig.json
This groups options so we can show the global options for each command.
Also adds the polymer logo :)
```
/\˜˜/   /\˜˜/\   
/__\/   /__\/__\    Polymer-CLI
/\  /   /\  /\  /\ 
/__\/   /__\/  \/__\  The multi-tool for Polymer projects
\  /\  /\  /   /\  /
\/__\/__\/   /__\/   Usage: `polymer <command> [options ...]`
\  /\  /   /\  /  
\/__\/   /__\/   
Available Commands
build		Builds an application-style project
help		Shows this help message, or help for a specific command
init		Initializes a Polymer project
lint		Lints the project
serve		Runs the polyserve development server
test		Runs web-component-tester
Global Options
--env                 The environment to use to specialize certain commands, like build             
--entrypoint          The main HTML file that will requested for all …
```
> Prettify the main help screen

- custom_typings/plylog.d.ts
- package.json
- src/build/analyzer.ts
- src/build/build.ts
- src/build/bundle.ts
- src/build/logger.ts
- src/build/prefetch.ts
- src/build/stream-resolver.ts
- src/build/sw-precache.ts
- src/build/uglify-transform.ts
- src/commands/build.ts
- src/commands/help.ts
- src/commands/init.ts
- src/commands/lint.ts
- src/commands/serve.ts
- src/init/github.ts
- test/commands/cli_test.js
Everything old is using the new logger. All thats left to move over is within the smaller packages that polymer-cli pulls in.
> Move all command logging to use new logger

- src/build/analyzer.ts
- src/build/bundle.ts
- test/build/analyzer/entrypoint.html
- test/build/analyzer/shell.html
- test/build/analyzer_test.js
- test/build/bundle_test.js
> Only analyze entrypoint if the build doesn’t have shell and fragments.

- package.json
- src/commands/serve.ts
> serve: -o opens app-shell projects to the entrypoint, not the component

- src/init/application/application.ts
- src/init/element/element.ts
- test/init/application_test.js
- test/init/element_test.js
- test/init/github_test.js
This bug was introduced by a breaking change in `mem-fs-editor`/`ejs`, that caused a previously supported behavior to throw. While original behavior may be restored downstream, we can fix this problem for ourselves today with this PR. See https://github.com/Polymer/polymer-cli/issues/206#issuecomment-221736928 for more info.
> Update call to copyTpl() to not throw in latest ejs

- src/args.ts
- src/polymer-cli.ts
- test/commands/cli_test.js
Fixes #189. Also gets rid of the last, now-unnecessary manual args parsing and replaces it with our more robust global-argument handling.
> Fix issue where polymer-cli throws when help flag is provided alone

- package.json
This is causing npm warnings on install
> Remove duplicate temp dependency in package.json

- gulpfile.js
This will allow polymer-cli to lint, build, and publish properly.
@justinfagnani suggest merging and pushing out a new patch version asap
> Fix broken depcheck task, use promise interface instead of callback

- gulpfile.js
- package.json
element & application templates are now internal to polymer-cli.
I'll add a deprecation notice to the `generator-polymer-init` README as well.
/cc @garlicnation
> Remove unused generator-polymer-init dependency

- src/polymer-cli.ts
- src/project-config.ts
- test/commands/lint_test.js
- test/config/project-config_test.js
I was running into problems testing different commands with different configurations, so I've refactored `polymer-cli` & `project-configuration` to read from an optional configuration object when given, instead of always reading directly from file.
#232 illustrates this usefulness, which I've split out from this work for clarity.
/cc @justinfagnani @garlicnation
> Refactor project-config to make polymer-cli testable /w configuration

- custom_typings/slash.d.ts
- src/build/bundle.ts
- test/build/bundle_test.js
Fixes #222
Previously, we were relying on path.posix.normalize() to convert unix & windows paths to the posix path format, to be returned as a URL path. However, path.posix.normalize() doesn't convert windows paths to posix. Example:
```
> path.posix.normalize('/src/123.html')
'/src/123.html'
> path.posix.normalize('\\src\\123.html')
'\\src\\123.html // expected url format `/src/123/html`
```
Both @justinfagnani  and I have looked into this, and the conclusion is that Node does not support this conversion natively. 
This commit adds the [slash](https://www.npmjs.com/package/slash) library to handle this conversion instead. This is a simple, well-supported package used by babel and some other major projects.
Our original worry was that escaped back slashes would be incorrectly converted, …
> Fix build bundling on windows

- src/build/analyzer.ts
- src/build/bundle.ts
- src/build/url-from-path.ts
- test/build/bundle_test.js
- test/build/url-from-path_test.js
This splits our `urlFromPath()` logic out of the bundler and into it's own module. This allows us to add back the proper license for the slash library, as well as clean up some duplicate code by refactoring analyzer to use the module as well.
/cc @garlicnation
> Split url-from-path logic out and into its own file

- package.json
- src/build/build.ts
The function we were using liftoff for was mostly delegated to findup
a dependency we are already using. This replaces liftoff with a findup-
only implementation, allowing us to remove liftoff (and it's ~50 deps)
from our dep tree.
Also adds some logging.
/cc @garlicnation
> Removes unneccesary liftoff dependency

- custom_typings/yeoman-environment.d.ts
- package.json
- src/commands/init.ts
- test/commands/init_test.js
Refactors InitCommand to make it easier to test and implements tests for it.
This was requested in #177, and the commented-out lines in the test will be uncommented as part of that PR.
> Tests for InitCommand

- bin/polymer.js
- package.json
Yeoman, Bower, web-component-tester, and a bunch of other familiar tools all use this tool to update users when their CLI is out of date. This should help version proliferation and solve headaches  for both users and developers (support costs).
/cc @garlicnation @justinfagnani
> Add update-notify to notify users when their cli is out of date

- src/commands/init.ts
Fixes #176, Supersedes #177 
Explicitly uses findup's synchronous interface. It was previously accidentally using the async interface and as a result, third-party generators were failing. Also adds debug logging because integrations are hard.
> specify the sync interface when searching templates for package.json

- src/init/element/templates/_element.html
Currently there is no demo reference in the element template.
Thus when creating a new element and serving it, there is no demo option, although the demo folder and demo template are created. It will be more consistent to include the demo reference (`@demo`) given that the demo template is provided.
> Add demo and description for element template

- src/commands/lint.ts
- src/commands/serve.ts
- src/commands/test.ts
- src/polymer-cli.ts
This moves the last of the commands  (besides init, which is complex enough to get its own PR) to use lazy dependency loading. We weren't able to move these previously because they were needed on load for our CLI argument definitions.
This (/w init fixed as well) drops our startup time from the original `~1.6s` down to `~0.2s`. booyah!
> Move last of the old commands to load their dependencies at runtime

- src/commands/lint.ts
- test/commands/lint_test.js
*NOTE: this is built off of the project-config work I just pushed into #231, so the "files changed" is currently a little noisy. See the individual commit for less noise.*
This adds support for linting of explicit files via the `input` default argument. This has been supported in our [polymer documentation](https://github.com/Polymer/docs2/blob/master/app/1.0/docs/tools/polymer-cli.md#lint-elements-lint) & README but was never actually supported by our code.
~~This also fixes an issue that seems to have been introduced with the Windows path fixes, by removing the leading slash that polylint was not expecting.~~ Pulling into its own PR
Fixes #227
/cc @justinfagnani @garlicnation
> Add input support for lint command

- src/init/application/templates/test/_element/_element_test.html
- src/init/element/templates/test/_element_test.html
`let` makes non ecma script 6 compliant browsers ignore the test (tested using Safari Version 9.1.1)
> assign element using `var` instead of `let`

- package.json
- src/commands/build.ts
- src/commands/help.ts
- src/commands/init.ts
- src/commands/lint.ts
- src/commands/serve.ts
- src/init/init.ts
- test/commands/init_test.js
- test/init/init_test.js
> *Whoops, looks like you can't reopen the original PR once closed. See https://github.com/Polymer/polymer-cli/pull/246 for past discussion (most of it outdated)*
There was considerable configuration/boilerplate brought into the `init` command tests, as a workaround to how self-contained and complex the command was. This refactoring pulls the main init logic out of the command itself, which has several benefits to our architecture:
- Removes the mockery dependency that was added for testing the original code 
- Reduces startup time considerably by delaying yeoman loading until the init command is run
- Keeps the command small and singular in focus
> Refactor init command tests and make the cli commands more testable

- custom_typings/command-line-args.d.ts
- custom_typings/command-line-commands.d.ts
- custom_typings/command-line-usage.d.ts
- package.json
- src/commands/build.ts
- src/commands/help.ts
- src/polymer-cli.ts
- test/commands/cli_test.js
- tsconfig.json
The command-line-* suite of libraries went through a major redesign for v1.0. This PR uses the new suite of tools, all updated to their latest versions.
> Update command-line-* suite of dependencies, refactor to accomodate

- package.json
- src/build/build.ts
With the new build pipeline, gulp is unneccesary as a regular dependency. Instead, we can use vinyl-fs directly and greatly reduce our dependency graph. (internally, `gulp.dest` is just a direct reference to `vinyl-fs.dest`)
See http://npm.anvaka.com/#/view/2d/gulp (212) vs. http://npm.anvaka.com/#/view/2d/vinyl-fs (89)
> replace unneccesary gulp dependency with vinyl-fs

- CHANGELOG.md
- package.json
- replace unneccesary gulp dependency with vinyl-fs
- polymer-build@v0.4.0 fixes build path issues
- fix bug where `--version` flag threw an exception
> [RELEASE] v0.14.0

- src/init/init.ts
Needs a new PSK release of https://github.com/PolymerElements/polymer-starter-kit/tree/app-drawer-migration, but it should be safe to merge this without being blocked by that.
/cc @robdodson @justinfagnani & the psk team
> Replace app-drawer-layout with polymer-starter-kit

- src/init/application/templates/.gitignore
- src/init/element/templates/.gitignore
To make sure the user does not accidentally commit the `bower_components` folder when pushing a new element/application to git.
> Add .gitignore to init templates

- src/project-config.ts
- test/config/polymer.json
- test/config/project-config_test.js
Previously, `root` only supported full system file paths. This made the option useless in a shared project with a shared polymer.json file. 
Now we support paths relative to the current working directory where the CLI is run.
/cc @robdodson @justinfagnani
> support relative root path in polymer.json

- .travis.yml
- gulpfile.js
- package.json
- 'init' & 'typings' are going away in #411
- remove 'build-all', now just use 'test'
/cc @justinfagnani @rictic
> cleanup gulp tasks & npm scripts

- custom_typings/yeoman-environment.d.ts
- src/init/init.ts
I looked into adding a test but because we call lookup() in the same function scope where we create the Env object it's not easy. Since this error [never actually happens](http://yeoman.io/environment/resolver.js.html#line49) I'm okay with leaving this untested for now, unless anyone feels strongly against.
/cc @justinfagnani @rictic
> add back env.lookup() error handling

- custom_typings/merge-stream.d.ts
- src/build/build.ts
After merging I was still getting errors from `merge-stream` for not having a type declaration, so I bit the bullet and added one. After this polymer-cli should be building without errors.
/cc @rictic @justinfagnani
> add custom typescript declaration for merge-stream

- src/init/init.ts
`createYeomanEnvironment()` returns a promise, but a couple callers weren't updated to await it, resulting in a runtime error when they tried to access methods not available on a promise.
> Fix runtime error on `polymer init`

- .clang-format
- package.json
- src/analyze/analyze.ts
- src/args.ts
- src/build/build.ts
- src/build/optimize-streams.ts
- src/build/prefetch.ts
- src/build/streams.ts
- src/build/sw-precache.ts
- src/commands/analyze.ts
- src/commands/build.ts
- src/commands/command.ts
- src/commands/help.ts
- src/commands/init.ts
- src/commands/install.ts
- src/commands/lint.ts
- src/commands/serve.ts
- src/commands/test.ts
- src/environment/environment.ts
- src/environments/environments.ts
- src/environments/reyserve.ts
- src/github/github.ts
- src/init/application/application.ts
- src/init/element/element.ts
- src/init/github.ts
- src/init/init.ts
- src/install/install.ts
- src/polymer-cli.ts
***Only merge when there are no outstanding PRs, and remember to run `npm run format` after merging!***
/cc @rictic @justinfagnani
> add common clang-format rules

- src/args.ts
- src/build/optimize-streams.ts
- src/commands/analyze.ts
- src/commands/build.ts
- src/commands/command.ts
- src/commands/help.ts
- src/commands/init.ts
- src/commands/install.ts
- src/commands/lint.ts
- src/commands/serve.ts
- src/commands/test.ts
Looks like these weird imports were just copy-pasted around the different commands.
/cc @rictic @justinfagnani
> import fixups, and adding missing licence headers

- CHANGELOG.md
Cleaned up the CHANGELOG for the pre-release.
~~REMEMBER TO REBASE AND MERGE so that the version number itself lives directly on master and not a merged-in branch.~~ We've removed the version bump from this PR, so that np can own that step.
/cc @justinfagnani @rictic @usergenic
> [RELEASE PR] v0.18.0-alpha.7

- src/build/build.ts
- src/commands/build.ts
Clarified this build flag since a lot of people (myself included) weren't sure what it was doing. Also confirmed it's still working as intended.
> Clarify `--add-prefetch` build flag

- CHANGELOG.md
- src/commands/init.ts
- src/init/init.ts
- test/unit/init/init_test.js
- test/unit/init/package.json
The generator name was parsed from the directory name (`./generator-polymer-init-foo/` --> `"foo"`), and this name was given to all sub-generators in the directory, regardless of their individual `package.json` config for `name`, which made them indistinguishable without descriptions. Technically, Yeoman generators are supposed to be named based on their `package.json` config [[1]](http://yeoman.io/authoring/).
```
generator-polymer-init-my-app
├── generators
│   ├── foo
│   │   ├── index.js
│   │   ├── package.json   # name: 'polymer-init-foo-el', description: 'My foo element'
│   │   └── templates
│   │      └── _element_test.html
│   └── bar
│       ├── index.js
│       ├── package.json   # name: 'polymer-init-bar-el', description: 'My bar element'
│       └── templates
│          └── …
```
> Fix generator names

- appveyor.yml
- npm-shrinkwrap.json
- package.json
This should get us more repeatable tests and bug reports, and reduces npm install times by ~15%.
`np` will regenerate the shrinkwrap for every release if one already exists, so this gets things started.
> Add a npm-shinkwrap.json file

- src/init/init.ts
- test/unit/init/init_test.js
Follow up from https://github.com/Polymer/polymer-cli/pull/472. 
We are now resolving bundled generators properly, but @justinfagnani pointed out that the `polymer-starter-kit-` prefix that is stripped out is important info. This PR removes that stripping.
/cc @justinfagnani @tony19
> stop stripping "polymer-starter-kit" from those templates

- src/build/build.ts
- src/build/optimize-streams.ts
- src/build/streams.ts
- src/commands/build.ts
This PR addresses two problems:
- All the build options had gotten pretty confusing, and assumed a world where each language only had one optimizer. This PR cleans up the CLI commands and simplified the optimize options that the main build function accepts.
- Constructing our optimize stream inside of pipes and gulp if's was too limiting. We now call out to `getOptimizeStreams` to calculate and return the optimize streams that we need.
This PR should be a noop functionality-wise, and prepares for a much easier diff in https://github.com/Polymer/polymer-cli/pull/525.
> Cleanup how optimize streams work, in preparation for babel stream

- package.json
- src/build/build.ts
- src/build/optimize-streams.ts
- src/commands/build.ts
- src/environment/environment.ts
- src/environments/reyserve.ts
This PR adds support for build configurations stored in a user's `polymer.json`. See [Build Permutations Design Doc](https://docs.google.com/document/d/1mD1cVhxdxY-bUsGBX44anC1875Afx7UHue4uRCNVc4o) for design overview.
*Note: Because of https://github.com/Polymer/polymer-build/issues/113, we need to create new instances of polymer-build projects for each build. This adds unnecessary reads and file analysis for each additional build. Once this is no longer required, we'll rewrite this logic to only use a single polymer-project instance for all builds.*
***Note: Requires release of https://github.com/Polymer/polymer-project-config/pull/5. Tests will pass once that is released.***
> Add support for polymer.json build configurations

- tsconfig.json
The latest version of typescript's standard library requires that the keys of a WeakMap be objects. So
interface WeakMap<K,V> { ... }
became
interface WeakMap<K extends object, V> { ... }
This conflicts with a declaration of WeakMap in the lodash typings (which the CLI depends on transitively).
Temporary workaround is to not typecheck libs.
More info: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14324
> Fix an issue when compiling with the latest TSC.

- test/integration/integration_test.js
This PR nests the current integration tests in an "init templates" test suite, and adds a new suite for  testing the templates in the `tools-starter-projects`.  It builds on top of @rictic's work in the `integration-tests` branch.
As a code comment mentions, there are two things needed before we can unskip these tests:
/cc @justinfagnani @rictic
> tools-sample-projects integration tests

- test/integration/integration_test.js
Now that tools-sample-projects is public we can connect them to the CLI tests.
/cc @rictic
> unskip integration tests

- src/init/application/templates/polymer-2.x/bower.json
- src/init/element/templates/polymer-2.x/bower.json
- test/integration/integration_test.js
Also skips failing integration tests that depended on external repos.
PSK is fixed in https://github.com/PolymerElements/polymer-starter-kit/pull/979
> Update Polymer 2.x templates to use RC1

- src/build/optimize-streams.ts
- test/unit/build/optimize_test.js
This is a quick fix so that we aren't blocking 2.0 release. After release, we should better address this (ex: as an option for the user to specify).
> skip optimizing for any web-component polyfills

- src/build/rewrite-webcomponents-loader.ts
- Fixes #605
- Old version of `webcomponentsjs` polyfills required the `webcomponents-es5-loader` when using compiled JS
- New version (release imminent) requires a separate polyfill before the loader, and now all scenarios use the default `webcomponents-loader`
- This PR changes the CLI from the old system to the new system
- Release will be coordinated with @azakus
> update webcomponentsjs polyfill to use the new custom-elements-es5-adapter

- gulpfile.js
- package.json
- src/build/rewrite-webcomponents-loader.ts
- src/commands/lint.ts
- src/commands/serve.ts
- src/github/github.ts
- test/integration/install-variants_test.js
- test/integration/integration_test.js
- test/integration/lint_test.js
- test/integration/run-command.js
- test/unit/args_test.js
- test/unit/build/load-config_test.js
- test/unit/build/optimize_test.js
- test/unit/commands/cli_test.js
- test/unit/commands/help_test.js
- test/unit/commands/init_test.js
- test/unit/github/github_test.js
- test/unit/init/application_test.js
- test/unit/init/element_test.js
- test/unit/init/github_test.js
- test/unit/init/init_test.js
- test/unit/install/install_test.js
* Bump clang-format to 1.0.48.
* Fix find command in npm format script, which wasn't properly catching test JS.
* Include gulp.js in formatted files.
* Format everything.
> More clang-format.

- CHANGELOG.md
- src/init/application/templates/polymer-1.x/bower.json
- src/init/element/templates/polymer-1.x/bower.json
Updating the Polymer 1.x application and element templates to latest released version of WCT. Seems odd that cli and 2.0 were updated a while back but the element templates haven't.
Wasn't sure if we wanted to update them to the pre-release WCT 6 or not.
> Update WCT for Polymer 1.x templates

- src/init/application/templates/polymer-2.x/test/_element/_element_test.html
- src/init/element/templates/polymer-2.x/test/_element_test.html
The previous tests made the assumption that no classes would
be automagically added to the `<h2>` tags. This assumption
doesn't hold in firefox 52 and I suspect browsers where the
Shadow DOM polyfill is used.
The tests were changed to only test the innerHTML as opposed to
the outerHTML.
The CHANGELOG was not modified. An existing entry already
describes this change.
> Fix failing polymer 2 application and element tests

- .travis.yml
- CHANGELOG.md
- package.json
- yarn.lock
Because this is already being done downstream, we might as well announce it in Polymer CLI and make it explicit so that no one is surprised.
If we see demand from users for the latest tagged version of the CLI that still supports Node v4, we should branch from the commit right before polymer-build@v1.0.0 was updated and create a new npm `node4` release tag so that users can `npm install -g polymer-cli@node4`. But it's still tbd if the demand for this is there.
> remove node v4 support

- .travis.yml
- package.json
- src/init/element/templates/polymer-2.x/_element.html
- test/integration/integration_test.js
#672 We've seen a few issues now about broken tests due to our work on the 8+ bundled templates, and I just realized those integration tests are still commented out. This PR uncomments them.
Re-enabling these locally made `npm test` take several minutes longer, so I'm experimenting with moving them out of `npm test` and into a separate `npm run test:integration` command. Travis will still run them by default.
> reenable some integration tests

- package.json
- Fixes #679.
- A recent change to @types/node broke some interface compatibility relating to our usage of streams with gulpif (https://github.com/DefinitelyTyped/DefinitelyTyped/commit/915a86f88bc2aad2e1dd59e2fea5edb1603c3cd7#diff-8811b50169fd98160ad78b073b4d0163). Not sure yet what the underlying issue is, so this pins to the version we know works for now.
> Pin @types/node to 6.0.65 to fix build in short term.

- README.md
Resolves #677
README was very out of date, both in terms of CLI behavior and missing references to our new polymer-project.org documentation. I wrote the new README to be more focus and hopefully need less maintenance going forward.
The diff isn't super helpful since it's a rewrite, so here's a link to the full document: https://github.com/Polymer/polymer-cli/blob/ce1255bff15f7e076d364109b918b2cca2710cf5/README.md
Trying to get this merged today if possible for a `latest` release tomorrow, so please review!
> updated README for v0.18.0

- CHANGELOG.md
- package.json
- src/run.ts
- yarn.lock
- Closing the loop on yesterdays CLI wild goose chase into npm by removing this functionality
- This behavior was undocumented and has no useful purpose in our modern CLI.
- Please comment if you are using this behavior for anything / believe it should continue to be supported.
/cc @keanulee
> remove ability for CLI to resolve to run a different version of the CLI

- CHANGELOG.md
- bin/polymer.js
- Updates our version compatibility pre-check to check <v6
- also clarified & fixed up the documentation on the file
- Resolves #670 #683 
- Changelog updated
We forgot to update this check when we dropped Node.js support, and saw an uptick in user-reported "SyntaxErrors" caused by out of date Node versions. This will return the more helpful message.
(I'd love to test this via Travis but I can't think of way to do that well without seriously complicating the rest of our tests. Open to ideas if anyone can think of one.)
> update node.js helpful version pre-run check

- CHANGELOG.md
- package.json
- src/build/build.ts
- src/commands/build.ts
- yarn.lock
~~*Note: Tests will fail until https://github.com/Polymer/polymer-project-config/pull/17 is merged and released. Checkout locally and `npm link` until then.*~~
- Add support for build configuration "presets" (Design: #714)
- Improves build performance by using a single PolymerProject instance to read sources/deps
> Use a single polymerproject for build, add support for build presets

- CHANGELOG.md
- src/build/streams.ts
Check if the asynIterator is already defined, if not define it.
This fixes my issue in the case that it is already defined somewhere apparently.
closes: #728
> fix(build): Check if asyncIterator is already assigned.

- CHANGELOG.md
- package.json
- yarn.lock
- Fix the CLI preset flag.
- Fix an issue where compiling JS would crash in versions of node with native async iterators.
- `bundle` no longer emits any JS or CSS files which have been inlined into bundles.
> Update for release of 0.18.3

- package.json
- yarn.lock
This is failing in integration test. It looks like the test fragment file foo.html is appearing in the output, where it used to be omitted. Expected change?
> Bump polymer-build version to 1.3.0

- CHANGELOG.md
- Update element and application templates to latest stable versions
- Prefetch links are now compatible with bundler and differential serving w/ base tag hrefs in entrypoint documents.
> Updated CHANGELOG for 1.0.1 release.

- CHANGELOG.md
- src/init/application/templates/polymer-1.x/index.html
- src/init/application/templates/polymer-2.x/index.html
- test/unit/init/application_test.js
Propagate `description` entered from command line during `polymer init` for either application template to the `<meta name="description">` tag in `index.html`.
If the user doesn't enter a description, fall back to previous template of:
```html
<meta name="description" content="<app-name> description">
```
I wasn't sure of the best way to format this, so will happily change if wanted.
---
> Propagate `description` to `index.html` in application templates

- CHANGELOG.md
- src/build/build.ts
- One half of the fix to https://github.com/Polymer/polymer-cli/issues/788
- Previously the `bundle` property of a build definition was limited to `true|false`.  Now it can also be a bag of the options for bundler, so we can support 1.x projects that need `rewriteUrlsInTemplates` behavior or turn off script inlining or css inlining etc.
- Side note: The compiled JS code in this PR will function fine without the update to polymer-project-config and the existing polymer-cli will accept new polymer-project-config values, fortunately, due to the truthiness of objects.
- I did not bump the required polymer-project-config version number in the package.json, we can do that when prepping the release.
- https://github.com/Polymer/polymer-project-config/pull/36 is the PR that gets the new type def …
> Added support for optional polymer-project-config provision of bundler options

- CHANGELOG.md
- package.json
- test/integration/fixtures/build-with-preset/expected/es5-bundled/push-manifest.json
- yarn.lock
- Added support for optional polymer-project-config provision of bundler options instead of only boolean value for the `bundle` property of build definitions.  See the [Polymer Project Config 3.4.0 release notes](https://github.com/Polymer/polymer-project-config/pull/37) for details on new options available in polymer.json.
- Includes Polymer Build fixes to push-manifest generation and others.  See [Polymer Build 1.6.0 release notes](https://github.com/Polymer/polymer-build/pull/249).
- Includes Polymer Bundler fixes to shell strategy and others.  See [Polymer Bundler 2.2.0 release notes](https://github.com/Polymer/polymer-bundler/pull/573).
> Prepare for 1.3.0 release

- CHANGELOG.md
- yarn.lock
- Fixed [issue #710](https://github.com/Polymer/polymer-cli/issues/710) where the es5 custom elements adapter would not be added when bundling.
- Fixed [issue #767](https://github.com/Polymer/polymer-cli/issues/767) where hyphenated option names for `build` command were effectively ignored.
- These are bug fixes and should not impact docs in any way.
> Prepare release 1.3.1

- CHANGELOG.md
- src/commands/analyze.ts
- src/commands/build.ts
- src/commands/command.ts
- src/commands/help.ts
- src/commands/init.ts
- src/commands/install.ts
- src/commands/lint.ts
- src/commands/serve.ts
- src/commands/test.ts
- src/polymer-cli.ts
- test/unit/commands/help_test.js
- test/unit/commands/init_test.js
- test/unit/commands/install_test.js
- test/unit/install/install_test.js
Adds aliases to commands to accomplish things like `polymer i` for `polymer install`. Apologies if there is somethings wrong with the TypeScript. Haven't used it before.
```
$ polymer install -h
polymer install
installs Bower dependencies, optionally installing "variants" 
Alias(es)
i 
Command Options
--variants    Whether to install variants 
--offline     Don't hit the network       
Global Options
--env type                      The environment to use to specialize certain commands, like build     
--entrypoint                    The main HTML file that will be requested for all routes.             
--shell string                  The app shell HTML import                                             
--fragment string[]             HTML imports that are loaded on-demand. …
```
> New: Add aliases for commands

- package-lock.json
- package.json
- Brings web-component-tester, polyserve and polymer-build all up-to-date so we have only one version of each.
- CHANGELOG.md was actually updated in a previous PR mentioning update of polymer-build to 2.0.0
> Updated package.json and package-lock.json to upgrade web-component-tester

- CHANGELOG.md
- Upgraded to Polymer Build ^2.0.0 which uses Polymer Bundler ^3.0.0.
- When no specific option is set for Bundler's `rewriteUrlsInTemplates` the CLI attempts to get the version of Polymer for the project using `bower`.  When Polymer 2.x is discovered, `rewriteUrlsInTemplates` is defaulted to `false`.  In case of Polymer 1.x or where version can not be identified, it defaults to `true`.  Any user settings override these defaults.
- Fix issue where negative `extraDependencies` globs were not working.
- test: Add support for WCT `config-file` option.
> Prepare 1.4.0 release

- CHANGELOG.md
- src/commands/serve.ts
- This flag passing is obnoxiously untestable.  I just tried several angles to verify it gets passed to polyserve in the server options, but I'd have to refactor the method altogether to test the flag passing and right now I just want to patch this.
> Added npm flag to the passed options.

- CHANGELOG.md
- Fixed the `polymer serve --npm` option.
No docs changes needed (minor bug fix)
> Updated CHANGELOG.md for the 1.4.1 release.

- CHANGELOG.md
- package-lock.json
- package.json
- yarn.lock
- Added support for `polymer test --npm` option.
- Fix issue where the `--fragment` flag was being ignored.
> Updated package.json and locks and CHANGELOG for 1.5.0 release.

- CHANGELOG.md
- Upgraded web-component-tester to v6.1.3 to address yarn installation issues.
> Updated CHANGELOG for 1.5.2 release.

- CHANGELOG.md
- package-lock.json
- package.json
- yarn.lock
- Upgraded web-component-tester to v6.1.5 to address IE11 issues.
> Updated CHANGELOG and package files to update wct to 6.1.5 to fix ie11 issue.

- CHANGELOG.md
- package-lock.json
- package.json
- yarn.lock
- Upgraded web-component-tester to v6.2.0 and polyserve 0.22.1 for better ES module support.
- No expected docs impacting features in release.  This just upgrades wct and polyserve.
> Prepare Release 1.5.5

- CHANGELOG.md
- package.json
- src/build/optimize-streams.ts
- test/unit/build/optimize_test.js
- yarn.lock
Installing the polymer-cli showed the following message:
```
babili has been renamed to babel-minify. Please update to babel-preset-minifybabel-preset-minify
```
This PR upgrades `babel-preset-babili` to the new name and fix breaking changes from 0.1.0. The unsafe option was removed and I updated the options to reflect the equivalent behavior. One change that was apparent was the removal of parenthesis from arrow functions (see the changed test). I am not sure if this is a bug or change in behavior of babili.
> Upgrade babili preset to new package name

- package.json
package.json is currently requiring `"request": "^2.72.0"` but only `"@types/request": "0.0.39"` along with it. (https://www.npmjs.com/package/@types/request lists 2.0.3 as the latest.)
I believe this can cause typescript error TS2430 for projects that depend on `polymer-cli`, see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17171 for an example. At least, I just hit this, and updating to the latest `@types/request` fixes it for me.
> Update to latest @types/request

- custom_typings/bower.d.ts
- src/build/build.ts
When building, polymer-cli uses 'bower list' to determine the current Polymer version in order to
set the 'rewriteUrlsInTemplates' option. However, 'bower list' by default will attempt to read
from the underlying package source (since it's typically used at the command-line to see if any
package has upgrades available). This behavior is undesirable (and unnecessary), particularly in CI.
I've also updated the TS custom_typing to match the actual bower list command signature
> Build: determine Polymer version via bower list using offline option

- CHANGELOG.md
- gulpfile.js
- package-lock.json
- package.json
- src/commands/lint.ts
- src/lint/lint.ts
- src/test/integration/lint_test.ts
> Implement `polymer lint --watch`

- CHANGELOG.md
- bin/polymer.js
- package-lock.json
> New: Check node version based on package.json

- src/init/application/templates/polymer-2.x/test/_element/_element_test.html
- src/init/element/templates/polymer-2.x/demo/index.html
- src/init/element/templates/polymer-2.x/test/_element_test.html
- src/init/element/templates/polymer-2.x/test/index.html
The Polymer v2.x init element should use the `webcomponents-loader.js`, right?
> Use webcomponents-loader.js in the init element

- tsconfig.json
Stubbed my toe on an implicitly `any` `this`. This will opt us into all the strictness.
> Use strict type checking.

- src/test/unit/commands/cli_test.ts
- src/test/unit/commands/help_test.ts
- src/test/util.ts
This captures all non-plylog output and lets us assert on it rather than logging it from the test runner.
It does not intercept plylog, as plylog is really hard to intercept. For the editor service, when it was a hard requirement, the only way I was able to do it was by importing a special log interceptor module before any plylog-using modules.
> Reduce the amount of noise in test output.

- CHANGELOG.md
- src/commands/serve.ts
- src/test/unit/commands/cli_test.ts
Fixed issue where the `--module-resolution` wasn't being handled for the `serve` command.
Prepare 1.7.0-pre.2
- [c] CHANGELOG.md has been updated
> Fix serve with --module-resolution and prepare release 1.7.0-pre.2

- .travis.yml
- package.json
This change improves Travis build times on pull requests. It does this by:
- caching `node_modules/`. `npm install` is still run and used, it just starts from the last builds cached `node_modules`.
- uses parallel builds to run smoke tests and integration tests.
> Speed up Travis builds from 13 minutes to 5 minutes
