Polymer/polymer-cli

- README.md
- custom_typings/web-component-tester.d.ts
- package.json
- src/commands/test.ts
- src/polytool.ts
- tsconfig.json
> Add test command

- package.json
- src/commands/lint.ts
- src/polytool.ts
- tsconfig.json
> Add lint command

- package.json
Hi, the `resolve` package is missing in the `package.json` file.
Regards.
> Add 'resolve' package

- .travis.yml
- package.json
- src/commands/init.ts
> add basic testing to check dependencies

- package.json
- src/build/build.ts
- src/build/logger.ts
- src/build/optimize-pipe.ts
- test/build/optimizepipe_test.js
- test/build/stream-resolver_test.js
- test/build/uglify-transform_test.js
optimizePipe now has options
TODO: thread flags through from CLI
> Add css-slam and gulp-html-minifier for even more minification

- src/build/bundle.ts
`this.bundle.push` would push onto the already-closed `streamResolver`
pipe, which would drop the files on the floor.
> Make sure bundler pushes onto the correct pipe

- src/build/build.ts
> strip html comments by default

- src/build/bundle.ts
- test/build/bundle_test.js
> Bundle shared imports into the shell

- src/build/build.ts
- src/build/bundle.ts
- src/build/prefetch.ts
- tsconfig.json
> flat prefetch in shell, flat imports in entrypoints

- src/build/bundle.ts
Fixes #86 Entrypoints include themselves in unbundled build
> Remove entrypoint from list of its own dependencies

- src/build/sw-precache.ts
- test/build/precache_test.js
> only log broken sw-precache config if it exists

- src/polymer-cli.ts
- src/project-config.ts
- test/config/bower/bower.json
- test/config/polymer.json
- test/config/project-config_test.js
> Read from 'polymer.json' for project config

- package.json
- test/commands/cli_test.js
Meant to get this into the PR, just a small interface change for the tests
> bump plylog@0.3.0, small change

- src/build/analyzer.ts
- test/build/analyzer/a.html
- test/build/analyzer/b.html
- test/build/analyzer/shared-1.html
- test/build/analyzer/shared-2.html
- test/build/analyzer_test.js
Fixes #111 Deduplicate dependency stuffing into fragments and
entrypoints
> Deduplicate fragment dependencies

- src/build/build.ts
- src/commands/lint.ts
- src/polymer-cli.ts
- src/project-config.ts
> Wire up the project config into the lint command

- src/commands/init.ts
/cc @justinfagnani 
These are imported in the command below, to shave 1+ seconds off startup time
> Fix bad merge where old import statements were pulled in

- .eslintignore
- package.json
- test/.eslintrc.json
- test/build/analyzer_test.js
- test/build/bundle_test.js
- test/build/optimize_test.js
- test/build/precache/config.js
- test/build/precache_test.js
- test/build/stream-resolver_test.js
- test/build/uglify-transform_test.js
- test/config/project-config_test.js
- test/init/github_test.js
/cc @azakus @justinfagnani for review
> Update eslint configuration and make needed small fixes

- src/args.ts
- src/commands/serve.ts
- src/commands/test.ts
- src/polymer-cli.ts
> Let commands override properties of global argument definitions.

- src/build/build.ts
- src/commands/build.ts
New flag `--insert-dependency-links`
Fixes #138
> Make dependency stuffing optional

- src/build/build.ts
- src/build/bundle.ts
- src/build/sw-precache.ts
- src/build/uglify-transform.ts
- src/commands/build.ts
- src/commands/init.ts
- src/polymer-cli.ts
Log statements, ahoy!
/cc @justinfagnani @azakus
> Log debug info for the entire build process

- src/build/build.ts
- src/build/optimize.ts
- src/commands/build.ts
Fixes #11 Optionally remove whitespace after vulcanization of css
Forward collapseWhitespace option with `--html.collapseWhitespace`
> Minify HTML even more!

- src/commands/init.ts
Running through some workflows, the current wording on the template select prompt felt awkard to me. Some of the descriptions didn't seem to do their templates justice either. 
This PR rewrites them to better explain what each template does and why you would choose it. Happy to bikeshed on any of them, as this was just my best attempt at each.
/cc @justinfagnani @azakus
> reword first init prompt

- .gitignore
- custom_typings/hydrolysis.d.ts
- src/build/analyzer.ts
- src/build/build.ts
- src/build/sw-precache.ts
> add script precache

- src/github/github.ts
> Fix issue where authorization header is set on null token

- src/github/github.ts
This code will better handle unexpected responses from Github, alerting the user instead of silently failing.
> Handles and properly alerts for unexpected github responses

- src/commands/init.ts
> Workaround buggy window terminal prompts

- src/init/application/templates/index.html
- src/init/application/templates/manifest.json
> Add a web app manifest to the application template

- README.md
> Update README section on building from source

- src/build/bundle.ts
This is in preparation for the Windows fix I've just completed. I'd
like to push these separately so that the windows fix can be as
concise as possible.
In this commit I added logging that helps detect the issue of missing
duplicate matches during bundling. I also renamed the path/osPath
variable names to be more intuitive (`path` now refers to the path
library).
This should have no effect on behavior.
/cc @garlicnation @justinfagnani
> small renaming and adding of logging to build/bundle

- custom_typings/github.d.ts
- package.json
- src/github/github.ts
- test/init/github_test.js
0.2.4 -> 1.1.0, comes with a small interface change
> github@1.1.0

- package.json
- tsconfig.json
- typings.json
_This concludes our dependencies update process. We hope you have enjoyed the experience, and look forward to updating again real soon._ 
> gulp-typings@2.0.0

- src/build/url-from-path.ts
Looks like a relic from development that snuck into the PR
> remove unneccesary console.log statement

- CHANGELOG.md
- package.json
> [RELEASE] v0.12.0

- bin/polymer.js
Built off of https://github.com/Polymer/polymer-cli/pull/316, includes 1 recommended fix so that we can get this in in the next version.
Props to @pmaudsley for the majority of the work!
> Send an error code on polymer command run error

- CHANGELOG.md
- README.md
- package.json
> [RELEASE] v0.13.0

- custom_typings/github.d.ts
- custom_typings/hydrolysis.d.ts
- custom_typings/web-component-tester.d.ts
- src/build/optimize-streams.ts
- src/build/prefetch.ts
- src/build/sw-precache.ts
- src/github/github.ts
- src/init/init.ts
- src/polymer-cli.ts
- src/project-config.ts
- test/build/optimize_test.js
- test/init/github_test.js
- test/init/init_test.js
(from this comment: https://github.com/Polymer/polymer-cli/pull/320#discussion_r73040415)
> rename `err` & `e` objects to common `error` naming scheme

- src/polymer-cli.ts
- test/commands/cli_test.js
Fixes #333
Also adds implicit return type to run() function, plus tests.
> return resolved promise on version flag

- src/project-config.ts
- test/config/polymer-invalid.json
- test/config/project-config_test.js
> Fail build immediately for invalid polymer.json

- src/args.ts
- src/build/build.ts
- src/commands/build.ts
- src/project-config.ts
- test/config/polymer.json
- test/config/project-config_test.js
Fixes #346 #376
~~WIP, still needs tests!~~
/cc @justinfagnani @robdodson
> Update config to support newer polymer.json build properties

- src/init/init.ts
- test/init/init_test.js
A fix for #351 (see issue for background on fix)
/cc @justinfagnani @robdodson
> stop showing undefined template description

- README.md
> Add missing polymer.json fields in README

- src/init/application/application.ts
> Fix issue where application element name always used dir default

- package.json
Upgrade to polyserve 0.13.0
Add node typings
> Fix tsc errors

- custom_typings/web-component-tester.d.ts
- src/commands/test.ts
- src/polymer-cli.ts
> Properly exit on test failure, uncaught exceptions

- src/build/build.ts
no behavior change, just a big indentation change and cleaner code
> convert build command to use async-await

- package.json
- src/build/build.ts
Resolves #193
Inspired by @chuckh's work on https://github.com/PolymerElements/polymer-starter-kit/pull/886
> Clear the build directory before building

- README.md
/cc @justinfagnani @rictic @usergenic
> make community templates visible in README

- package.json
- src/args.ts
- src/commands/serve.ts
- src/polymer-cli.ts
- test/unit/args_test.js
> Use polyserve’s argument definitions

- .travis.yml
- CHANGELOG.md
Resolves #481 
Adding as todo for other repos as well
> remove support for node v5, add support for node v7

- CHANGELOG.md
- package.json
> Upgrade wct to 6.0.0-prerelease.1

- test/unit/init/init_test.js
> Add regression tests for #471

- README.md
As discussed [here](https://github.com/Polymer/polymer-cli/issues/300).
> Added note about --hostname

- src/build/optimize-streams.ts
> print error.message with optimize errors

- .travis.yml
Remove duplicate npm install, Travis does this automatically already.
Fixes #520
> Remove duplicate npm install in Travis configuration

- README.md
> Correct a couple typos

- src/build/build.ts
- src/commands/build.ts
> Convert build to single build stream

- CHANGELOG.md
- src/init/application/application.ts
- src/init/element/element.ts
- src/init/github.ts
- test/unit/init/application_test.js
- test/unit/init/element_test.js
> Fix https://github.com/Polymer/polymer-cli/issues/186

- package.json
> Update to polymer-build@v0.6.0

- CHANGELOG.md
Getting this out to fix broken `polymer test` command on CI from bad dependency.
> [RELEASE] v0.18.0-alpha.9

- src/commands/analyze.ts
- src/commands/build.ts
- src/commands/help.ts
- src/commands/init.ts
- src/commands/install.ts
- src/commands/lint.ts
- src/commands/serve.ts
- src/commands/test.ts
- src/init/init.ts
> Give types to lazy loaded libraries

- src/init/application/templates/polymer-2.x/src/_element/_element.html
- src/init/element/templates/polymer-2.x/_element.html
Small fix to make the init templates work with the new Polymer 2.0.0-rc.1 style
> Use properties getter with 2.0

- CHANGELOG.md
- src/init/init.ts
- test/integration/integration_test.js
> add polymer 2.0 psk to the init command template list

- CHANGELOG.md
- src/polymer-cli.ts
- test/unit/commands/help_test.js
> automatically include wc polyfills as extraDependencies

- src/init/application/templates/polymer-2.x/index.html
- src/init/element/templates/polymer-2.x/index.html
> Change Polymer 2.0 templates to use webcomponents-loader.js

- CHANGELOG.md
- src/build/build.ts
- src/build/prefetch.ts
- src/build/rewrite-webcomponents-loader.ts
> Rewrite webcomponents loader script include

- CHANGELOG.md
- yarn.lock
My wording in the changelog is worth checking, I snuck it in the previous PR after review.
> Prepare to release pre.14

- src/init/application/templates/polymer-2.x/bower.json
- src/init/application/templates/polymer-2.x/src/_element/_element.html
> Polymer 2 app template fixes

- CHANGELOG.md
- src/build/prefetch.ts
- test/unit/build/prefetch_test.js
* Adds a test and a little refactoring.
* Fixes #600.
> Handle relative URLs correctly with insert-prefetch-links.

- CHANGELOG.md
- src/init/application/templates/polymer-2.x/src/_element/_element.html
- src/init/application/templates/polymer-2.x/test/_element/_element_test.html
- src/init/element/templates/polymer-1.x/_element.html
- src/init/element/templates/polymer-2.x/_element.html
- src/init/element/templates/polymer-2.x/test/_element_test.html
> fix polymer-2 element and application tests

- CHANGELOG.md
- src/init/element/templates/polymer-2.x/bower.json
- src/init/element/templates/polymer-2.x/index.html
> Fix broken polymer-2-element serve page

- CHANGELOG.md
- src/init/application/application.ts
- src/init/application/templates/polymer-2.x/src/_element/_element.html
- src/init/element/element.ts
- src/init/element/templates/polymer-2.x/_element.html
- test/unit/init/application_test.js
- test/unit/init/element_test.js
> create UpperCamelCase class name from element name

- CHANGELOG.md
- src/init/application/templates/polymer-1.x/README.md
- src/init/application/templates/polymer-2.x/README.md
- src/init/element/templates/polymer-1.x/README.md
- src/init/element/templates/polymer-2.x/README.md
> update template readmes

- CHANGELOG.md
> Prepare v0.18.0 Release

- CHANGELOG.md
- package.json
- src/commands/serve.ts
Fixes https://github.com/Polymer/polyserve/issues/180.
> Pass entrypoint from polymer.json to polyserve.

- src/init/application/templates/polymer-2.x/src/_element/_element.html
> Fix polymer-2.x application paths

- src/init/element/templates/polymer-2.x/demo/index.html
Not sure if this warrants a changelog entry...
> Add missing <custom-style> to polymer-2-element demo template (#692)

- src/build/optimize-streams.ts
> Safe minify

- CHANGELOG.md
- package.json
- src/args.ts
> Update polyserve to 0.19.0

- CHANGELOG.md
- package.json
- src/build/build.ts
- yarn.lock
This change depends on these PRs, and will fail on Travis until they're released:
https://github.com/Polymer/polymer-build/pull/211
https://github.com/Polymer/polymer-build/pull/212
https://github.com/Polymer/polymer-project-config/pull/23
> Hook up basePath to service worker, push manifest, and base tag updater.

- CHANGELOG.md
> Updated CHANGELOG for 1.0.0 🎉

- README.md
> Correct `yarn global add ...` installation instructions

- CHANGELOG.md
- src/init/application/templates/polymer-1.x/bower.json
- src/init/application/templates/polymer-2.x/bower.json
- src/init/element/templates/polymer-1.x/bower.json
- src/init/element/templates/polymer-2.x/bower.json
Seems like this was missed in the 1.0.0 release and fixes #750
> Fix: Update dependencies for templates

- CHANGELOG.md
- package.json
- src/build/build.ts
- test/integration/fixtures/build-with-preset/expected/es5-bundled/service-worker.js
- yarn.lock
Fixes #761 (see there for context).
Will fail on Travis until https://github.com/Polymer/polymer-build/pull/230 is merged.
Also updates integration test and CHANGELOG to account for https://github.com/Polymer/polymer-build/pull/229.
> Don't set service worker or push manifest prefixes when basePath is set.

- CHANGELOG.md
> Prepare 1.1.0 release.

- CHANGELOG.md
- src/init/element/templates/polymer-2.x/polymer.json
> Updated lint rule to polymer-2 in the polymer-2-element template

- CHANGELOG.md
- src/init/init.ts
> Bump shop init template to 2.x and drop all 1.x templates.

- src/polymer-cli.ts
> Fix issue where user-provided globs weren't given priority, broke negatives

- src/commands/test.ts
You can now pass the WCT configfile via the polymer-cli
> Feat(wct): Added configfile option to the cli.

- CHANGELOG.md
- src/polymer-cli.ts
> Respect the `--fragment` argument for `build`

- CHANGELOG.md
- src/polymer-cli.ts
- test/integration/build_test.js
- test/integration/fixtures/fragment-variations/expected-default/default/index.html
- test/integration/fixtures/fragment-variations/expected-fragment-a/default/a.html
- test/integration/fixtures/fragment-variations/expected-fragment-a/default/index.html
- test/integration/fixtures/fragment-variations/expected-fragment-b/default/a.html
- test/integration/fixtures/fragment-variations/expected-fragment-b/default/b.html
- test/integration/fixtures/fragment-variations/expected-fragment-b/default/index.html
- test/integration/fixtures/fragment-variations/source/a.html
- test/integration/fixtures/fragment-variations/source/b.html
- test/integration/fixtures/fragment-variations/source/c.html
- test/integration/fixtures/fragment-variations/source/index.html
- Fixes issue https://github.com/Polymer/polymer-cli/issues/829 where the `--fragment` flag was being ignored.
- Original fix from commit by @6112
> Respect the '--fragment' argument for 'build' (#831)

- CHANGELOG.md
- package-lock.json
- package.json
- src/commands/test.ts
- Added support for `polymer test --npm` option.
> Support npm flag for test

- CHANGELOG.md
- package-lock.json
- package.json
- yarn.lock
- Updated package.json and lockfiles for wct 6.1.2 upgrade.
> Upgrade wct to 6.1.2

- CHANGELOG.md
> Updated CHANGELOG for 1.5.1 release.

- CHANGELOG.md
- package-lock.json
- package.json
- yarn.lock
- Upgraded web-component-tester to v6.1.3 to address yarn installation issues.
> Update wct to 6.1.3

- CHANGELOG.md
- package-lock.json
- yarn.lock
- Upgraded web-component-tester to v6.1.4 to address IE11 issues.
> Prepare release 1.5.3 of cli to get wct fix in.

- CHANGELOG.md
- src/init/element/templates/polymer-2.x/test/_element_test.html
> Update 2.0 element test to use ES6

- package-lock.json
- yarn.lock
Update lock files after the last dependencies changes (bower, etc).
> Update lock files

- CHANGELOG.md
- `yarn.lock` regenerated (#909)
- `package-lock.json` regenerated (#909)
> prepare release v1.5.7

- CHANGELOG.md
- package-lock.json
- package.json
- src/commands/lint.ts
- src/lint/lint.ts
- test/integration/fixtures/lint-fixes/polymer.json
- test/integration/fixtures/lint-fixes/subdir/nested-bad.html
- test/integration/fixtures/lint-fixes/toplevel-bad.html
- test/integration/lint_test.js
- test/integration/run-command.js
- yarn.lock
> Support lint --fix

- gulpfile.js
- package-lock.json
- package.json
- src/analyze/analyze.ts
- src/build/build.ts
- src/build/optimize-streams.ts
- src/commands/build.ts
- src/commands/lint.ts
- src/commands/test.ts
- src/github/github.ts
- src/init/init.ts
- src/test/unit/init/init_test.ts
I'm using `for await` in another PR and clang-format is unhappy with it before this PR.
> Update and re-run clang-format.

- README.md
- src/init/init.ts
- src/test/integration/fixtures/install-variants/bower_cache/f7f075fb0e2eb0ce17a7ed61f88773a8/1.7.0/.bower.json
- src/test/integration/fixtures/install-variants/bower_cache/f7f075fb0e2eb0ce17a7ed61f88773a8/1.7.0/bower.json
- src/test/integration/integration_test.ts
Now the PSK is in the Polymer organization:
https://github.com/Polymer/polymer-starter-kit
> PSK Organization update: PolymerElements > Polymer

- CHANGELOG.md
- src/args.ts
- src/test/unit/commands/serve_test.ts
>  Fix —-module-resolution default from polyserve overriding polymer.json

- npm-shrinkwrap.json
- package.json
> Fix missing gulp-if dependency.

- CHANGELOG.md
> Prepare 1.7.0-pre.4 release.
